'use client'
import { Box, Typography, useTheme } from '@mui/material'
import axios from 'axios'
import Head from 'next/head'
import { useEffect } from 'react'
import CustomTextField from 'src/components/text-field'
import { useSettings } from 'src/hooks/useSettings'

export default function Home() {
  const theme = useTheme()
  const { settings } = useSettings()
  console.log('theme', { theme, settings })

  return (
    <>
      <Head>
        <title>Lập trình thật dễ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <Box sx={{ margin: 6, width: '200px' }}>
        <CustomTextField helperText='Please enter your name' id='demo-helper-text-aligned' label='Name' />
      </Box> */}
    </>
  )
}
